/**
 * Generates supabase/migrations/0002_seed_content.sql from the TypeScript route
 * data, so the database and the app can never disagree about the journey.
 *
 *   node scripts/generate-seed.mjs
 *
 * The data modules only carry type-only imports, which esbuild strips, so each
 * one transpiles to plain ESM without needing the whole bundle graph.
 */
import { transform } from 'esbuild';
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => Number(v).toFixed(2);

async function load(file, exportName) {
  const src = await readFile(join('src/data', file), 'utf8');
  const { code } = await transform(src, { loader: 'ts', format: 'esm' });
  const dir = await mkdtemp(join(tmpdir(), 'lantrn-seed-'));
  const path = join(dir, 'mod.mjs');
  await writeFile(path, code, 'utf8');
  try {
    const mod = await import(pathToFileURL(path).href);
    return mod[exportName];
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

const destinations = await load('destinations.ts', 'destinations');
const characters = await load('characters.ts', 'characters');
const milestones = await load('milestones.ts', 'milestones');

const total = characters.reduce((sum, c) => sum + c.requiredMiles, 0);

const lines = [
  '-- ===========================================================================',
  '-- Route content. Generated by scripts/generate-seed.mjs — do not hand-edit.',
  '--',
  `-- ${destinations.length} destinations, ${characters.length} encounters, ${total} miles end to end.`,
  '-- Re-runnable: every statement upserts.',
  '-- ===========================================================================',
  '',
];

lines.push('insert into public.destinations (id, name, subtitle, description, order_index, palette) values');
lines.push(
  destinations
    .map(
      (d) =>
        `  (${q(d.id)}, ${q(d.name)}, ${q(d.subtitle)}, ${q(d.description)}, ${d.order}, ${q(
          JSON.stringify(d.palette),
        )}::jsonb)`,
    )
    .join(',\n') + '\non conflict (id) do update set',
);
lines.push(
  '  name = excluded.name, subtitle = excluded.subtitle, description = excluded.description,',
  '  order_index = excluded.order_index, palette = excluded.palette;',
  '',
);

lines.push(
  'insert into public.characters (id, name, epithet, description, required_miles, destination_id, order_index, note) values',
);
lines.push(
  characters
    .map(
      (c) =>
        `  (${q(c.id)}, ${q(c.name)}, ${q(c.epithet)}, ${q(c.description)}, ${n(c.requiredMiles)}, ${q(
          c.destinationId,
        )}, ${c.order}, ${q(c.note ?? null)})`,
    )
    .join(',\n') + '\non conflict (id) do update set',
);
lines.push(
  '  name = excluded.name, epithet = excluded.epithet, description = excluded.description,',
  '  required_miles = excluded.required_miles, destination_id = excluded.destination_id,',
  '  order_index = excluded.order_index, note = excluded.note;',
  '',
);

lines.push('insert into public.milestones (id, name, required_miles, description) values');
lines.push(
  milestones
    .map((m) => `  (${q(m.id)}, ${q(m.name)}, ${n(m.requiredMiles)}, ${q(m.description)})`)
    .join(',\n') + '\non conflict (id) do update set',
);
lines.push('  name = excluded.name, required_miles = excluded.required_miles, description = excluded.description;', '');

await writeFile('supabase/migrations/0002_seed_content.sql', lines.join('\n'), 'utf8');

console.log(
  `wrote supabase/migrations/0002_seed_content.sql — ${destinations.length} destinations, ` +
    `${characters.length} characters, ${milestones.length} milestones, ${total} miles`,
);
