-- ===========================================================================
-- Route content. Generated by scripts/generate-seed.mjs — do not hand-edit.
--
-- 5 destinations, 21 encounters, 1550 miles end to end.
-- Re-runnable: every statement upserts.
-- ===========================================================================

insert into public.destinations (id, name, subtitle, description, order_index, palette) values
  ('hidden-school', 'The Hidden School', 'A gap in the wall, and a castle across the water', 'It starts with a letter nobody can explain and ends at a gate that opens on its own. The shortest destination on the route, because the only job of this stretch is to get you out the door.', 0, '{"deep":"#1B2033","mid":"#464F78","glow":"#D4B36A"}'::jsonb),
  ('emerald-road', 'The Emerald Road', 'One long road, one green city', 'A single paved road through a country that makes no sense, walked in the company of three travellers who each believe they are missing something.', 1, '{"deep":"#14301F","mid":"#2F6B45","glow":"#7ECB8F"}'::jsonb),
  ('forgotten-north', 'The Forgotten North', 'A voice past the mountains, and the river at the end of it', 'North until the maps give up: a wood that has been sealed behind fog for a generation, a sea nobody crosses on foot, and a frozen river that kept every single thing that ever happened.', 2, '{"deep":"#0D2733","mid":"#2A6B84","glow":"#9BDDEE"}'::jsonb),
  ('thorn-castle', 'The Thorn Castle', 'A village, a wood, and a bargain', 'Out of a town that never understood you, through a wood that would rather you turned back, to a door that has been waiting a very long time.', 3, '{"deep":"#2B1520","mid":"#6E3348","glow":"#D48A9E"}'::jsonb),
  ('mountain-road', 'The Mountain Road', 'Carrying something back to the place that made it', 'The longest destination on the route, and the only one where the goal is to arrive empty-handed. Ash underfoot for the last two hundred miles.', 4, '{"deep":"#241A16","mid":"#6B3A2A","glow":"#D9764A"}'::jsonb)
on conflict (id) do update set
  name = excluded.name, subtitle = excluded.subtitle, description = excluded.description,
  order_index = excluded.order_index, palette = excluded.palette;

insert into public.characters (id, name, epithet, description, required_miles, destination_id, order_index, note) values
  ('letterbearer', 'The Letterbearer', 'Brings an invitation that should not exist', 'Turns up with a letter addressed to you in a hand nobody recognises, at an address you never gave anyone. Will not answer questions and will not leave until you read it.', 5.00, 'hidden-school', 0, null),
  ('platform-warden', 'The Platform Warden', 'Keeps the gap in the wall', 'Stands on a station concourse all day watching people walk past a doorway none of them can see. Nods once at the ones who can, and never twice.', 10.00, 'hidden-school', 1, null),
  ('lakekeeper', 'The Boneflyer', 'Pulls the carriage no one else can see', 'Waits in the traces after dark, wings folded, invisible to anyone who has never lost something. Gentle with the ones who can see it, and unbothered by the ones who cannot.', 15.00, 'hidden-school', 2, null),
  ('headmaster', 'The Headmaster', 'Already knew you were coming', 'Waits at the top of the steps with his hands behind his back, entirely unsurprised. Answers the question you meant to ask rather than the one you did.', 20.00, 'hidden-school', 3, null),
  ('strawman', 'The Strawman', 'Convinced he has no brains', 'Spends the whole road apologising for being stupid while quietly solving every problem the party runs into. Nobody has the heart to point it out.', 25.00, 'emerald-road', 4, null),
  ('rusted-woodsman', 'The Rusted Woodsman', 'Seized solid in the rain', 'Found mid-swing, frozen where he stood, waiting for somebody with an oil can. Weeps easily, which is the exact opposite of his stated problem.', 30.00, 'emerald-road', 5, null),
  ('timid-king', 'The Timid King', 'Loudest when most afraid', 'King of every beast on the road and terrified of all of them. The roar is real. So is the shaking underneath it.', 45.00, 'emerald-road', 6, null),
  ('man-behind-the-curtain', 'The Man Behind the Curtain', 'Smaller than advertised', 'Enormous voice, enormous smoke, enormous everything — until somebody pulls the drape back and finds an ordinary man working levers. Gives good advice anyway.', 50.00, 'emerald-road', 7, null),
  ('voice-past-the-mountains', 'The Voice Past the Mountains', 'Four notes, and only you can hear them', 'Starts as something you can almost ignore and becomes the only thing you can hear. Nobody else in the room reacts, which is how you know it is meant for you.', 60.00, 'forgotten-north', 8, null),
  ('ember-lizard', 'The Ember Lizard', 'Smallest thing here, and the most flammable', 'Sets a whole autumn wood alight because it panicked, then sits on your outstretched hand and calms down. Both facts are equally true.', 70.00, 'forgotten-north', 9, null),
  ('horse-of-the-deep', 'The Horse of the Deep', 'The crossing has to be ridden', 'Guards the water the way weather guards a mountain, without malice and without mercy. Will drown you twice before it agrees to carry you.', 80.00, 'forgotten-north', 10, null),
  ('river-that-remembers', 'The River That Remembers', 'Frozen, and it kept everything', 'A glacier that runs like water if you know how to listen. Every account of what really happened is in here, including the ones nobody wanted kept.', 90.00, 'forgotten-north', 11, null),
  ('bookseller', 'The Bookseller', 'The only one who understood', 'Keeps the small shop at the end of the square and lets you take the same volume home for the third time without a word about it.', 100.00, 'thorn-castle', 12, null),
  ('hollow-wolves', 'The Hollow Wolves', 'The stretch between the mill and the gates', 'Not one encounter but six, in a wood where the safe road ends. You do not meet them so much as get through them.', 110.00, 'thorn-castle', 13, null),
  ('rose-gardener', 'The Rose Gardener', 'Tends what the curse left behind', 'Still pruning a garden nobody visits, under glass, for a household that stopped counting years a while ago. Insists it will matter again.', 120.00, 'thorn-castle', 14, null),
  ('lord-of-thorns', 'The Lord of Thorns', 'Handling it badly', 'Enormous, furious, and profoundly embarrassed about all of it. Offers you the library by way of apology, which very nearly works.', 130.00, 'thorn-castle', 15, null),
  ('old-wanderer', 'The Old Wanderer', 'Grey cloak, worse news', 'Arrives unannounced, stays exactly as long as it takes to ruin your plans, and leaves you holding something you did not ask for.', 105.00, 'mountain-road', 16, null),
  ('sworn-companion', 'The Sworn Companion', 'Will not be left behind', 'Follows you into water he cannot swim, because the alternative was letting you go alone. Carries the pans, the rope, and eventually you.', 135.00, 'mountain-road', 17, null),
  ('creature-in-the-dark', 'The Creature in the Dark', 'Has been following you for weeks', 'Wants the thing you are carrying more than it has ever wanted anything, and knows the only road left. Both of those facts are useful to you.', 65.00, 'mountain-road', 18, 'A hidden encounter — deliberately shorter than the legs on either side of it.'),
  ('forgemaster', 'The Forgemaster', 'Made the thing you are carrying', 'Waits at the top of the ash, at the fire where it was poured. The whole route exists to bring you back to this door and leave with nothing.', 185.00, 'mountain-road', 19, 'The end of the quest itself. One encounter waits beyond it.'),
  ('hymnkeeper', 'The Hymnkeeper', 'Walks ahead, carrying the only light', 'Comes up the road at dusk swinging a lantern and singing something you half recognise. By the time he has gone past, a fair number of the people behind you are walking with him instead. Puts the light out when he is finished talking, and lets the dark do the rest of the work.', 100.00, 'mountain-road', 20, 'A coda. The quest ends at the fire; this is who is waiting on the road afterwards.')
on conflict (id) do update set
  name = excluded.name, epithet = excluded.epithet, description = excluded.description,
  required_miles = excluded.required_miles, destination_id = excluded.destination_id,
  order_index = excluded.order_index, note = excluded.note;

insert into public.milestones (id, name, required_miles, description) values
  ('m-10', 'First Ten', 10.00, 'Far enough that it stopped being a walk and started being a habit.'),
  ('m-25', 'Quarter Century', 25.00, 'The novelty has worn off and you kept going anyway.'),
  ('m-50', 'The Half Hundred', 50.00, 'A full destination behind you, and a route that no longer feels theoretical.'),
  ('m-100', 'Triple Digits', 100.00, 'One hundred miles on foot. Most people who start never see this number.'),
  ('m-250', 'The Long Middle', 250.00, 'Past the excitement, into the part that actually counts.'),
  ('m-500', 'Halfway Marker', 500.00, 'The stone by the road that tells you it is closer ahead than behind.'),
  ('m-1000', 'The Thousand', 1000.00, 'Four digits. There is no casual way to walk one thousand miles.'),
  ('m-1500', 'Fifteen Hundred', 1500.00, 'Past the end of the route and still moving.'),
  ('m-2500', 'The Far Count', 2500.00, 'A number that stops being a goal and starts being a fact about you.')
on conflict (id) do update set
  name = excluded.name, required_miles = excluded.required_miles, description = excluded.description;
